"""Catálogo geográfico de Guatemala para RULE-012 y RULE-013.

Departamentos según división político-administrativa oficial (22) y sus
municipios. La comparación se hace siempre con texto normalizado
(mayúsculas, sin tildes, sin espacios duplicados).
"""

DEPARTMENTS: dict[str, list[str]] = {
    "GUATEMALA": [
        "GUATEMALA",
        "MIXCO",
        "VILLA NUEVA",
        "SAN MIGUEL PETAPA",
        "VILLA CANALES",
        "AMATITLAN",
        "CHINAUTLA",
        "SAN JOSE PINULA",
        "SANTA CATARINA PINULA",
        "SAN JOSE DEL GOLFO",
        "SAN PEDRO AYAMPUC",
        "SAN JUAN SACATEPEQUEZ",
        "SAN RAYMUNDO",
        "CHUARRANCHO",
        "FRAIJANES",
        "PALENCIA",
        "SAN ANTONIO LA PAZ",
    ],
    "SACATEPEQUEZ": [
        "ANTIGUA GUATEMALA",
        "CIUDAD VIEJA",
        "JOCOTENANGO",
        "SUMPANGO",
        "SAN LUCAS SACATEPEQUEZ",
        "SANTIAGO SACATEPEQUEZ",
        "SANTO DOMINGO XENACOJ",
        "SAN BARTOLOME MILPAS ALTAS",
        "SANTA LUCIA MILPAS ALTAS",
        "MAGDALENA MILPAS ALTAS",
        "SANTA MARIA DE JESUS",
        "SAN MIGUEL DUENAS",
        "ALOTENANGO",
        "SAN ANTONIO AGUAS CALIENTES",
        "SANTA CATARINA BARAHONA",
        "PASTORES",
    ],
    "CHIMALTENANGO": [
        "CHIMALTENANGO",
        "SAN JOSE POAQUIL",
        "SAN MARTIN JILOTEPEQUE",
        "SAN JUAN COMALAPA",
        "SANTA APOLONIA",
        "TECPAN",
        "PATZUN",
        "PATZICIA",
        "POCHUTA",
        "SAN MIGUEL POCHUTA",
        "SAN ANDRES ITZAPA",
        "EL TEJAR",
        "YEPOCAPA",
        "ACATENANGO",
        "SANTA CRUZ BALANYA",
        "ZARAGOZA",
    ],
    "ESCUINTLA": [
        "ESCUINTLA",
        "SANTA LUCIA COTZUMALGUAPA",
        "LA DEMOCRACIA",
        "SIQUINALA",
        "MASAGUA",
        "TIQUISATE",
        "LA GOMERA",
        "GUANAGAZAPA",
        "SAN JOSE",
        "IZTAPA",
        "PALIN",
        "SAN VICENTE PACAYA",
        "NUEVA CONCEPCION",
    ],
    "SANTA ROSA": [
        "CUILAPA",
        "BARBERENA",
        "SANTA ROSA DE LIMA",
        "CASILLAS",
        "SAN RAFAEL LAS FLORES",
        "ORATORIO",
        "SAN JUAN TECUACO",
        "CHIQUIMULILLA",
        "TAXISCO",
        "GUAZACAPAN",
        "SANTA CRUZ NARANJO",
        "PUEBLO NUEVO VINAS",
        "NUEVA SANTA ROSA",
        "SANTA MARIA IXHUATAN",
    ],
    "SOLOLA": [
        "SOLOLA",
        "PANAJACHEL",
        "SANTIAGO ATITLAN",
        "SAN PEDRO LA LAGUNA",
        "SAN JUAN LA LAGUNA",
        "SANTA CATARINA PALOPO",
        "SAN ANTONIO PALOPO",
        "SAN MARCOS LA LAGUNA",
        "SANTA CRUZ LA LAGUNA",
        "SAN JOSE CHACAYA",
        "SANTA MARIA VISITACION",
        "SANTA LUCIA UTATLAN",
        "NAHUALA",
        "SANTA CATARINA IXTAHUACAN",
        "SANTA CLARA LA LAGUNA",
        "CONCEPCION",
        "SAN ANDRES SEMETABAJ",
        "SAN PABLO LA LAGUNA",
        "SANTIAGO SACATEPEQUEZ",
    ],
    "TOTONICAPAN": [
        "TOTONICAPAN",
        "SAN CRISTOBAL TOTONICAPAN",
        "SAN FRANCISCO EL ALTO",
        "MOMOSTENANGO",
        "SANTA MARIA CHIQUIMULA",
        "SANTA LUCIA LA REFORMA",
        "SAN BARTOLO AGUAS CALIENTES",
        "SAN ANDRES XECUL",
    ],
    "QUETZALTENANGO": [
        "QUETZALTENANGO",
        "SALCAJA",
        "OLINTEPEQUE",
        "SAN CARLOS SIJA",
        "SIBILIA",
        "CABRICAN",
        "CAJOLA",
        "SAN MIGUEL SIGUILA",
        "SAN JUAN OSTUNCALCO",
        "SAN MATEO",
        "CONCEPCION CHIQUIRICHAPA",
        "SAN MARTIN SACATEPEQUEZ",
        "ALMOLONGA",
        "CANTEL",
        "HUITAN",
        "ZUNIL",
        "COATEPEQUE",
        "COLOMBA",
        "SAN FRANCISCO LA UNION",
        "EL PALMAR",
        "PALESTINA DE LOS ALTOS",
        "LA ESPERANZA",
        "FLORES COSTA CUCA",
        "GENOVA",
    ],
    "SUCHITEPEQUEZ": [
        "MAZATENANGO",
        "CUYOTENANGO",
        "SAN FRANCISCO ZAPOTITLAN",
        "SAN BERNARDINO",
        "SAN JOSE EL IDOLO",
        "SANTO DOMINGO SUCHITEPEQUEZ",
        "SAN LORENZO",
        "SAMAYAC",
        "SAN PABLO JOCOPILAS",
        "SAN ANTONIO SUCHITEPEQUEZ",
        "SAN MIGUEL PANAN",
        "SAN GABRIEL",
        "CHICACAO",
        "PATULUL",
        "SANTA BARBARA",
        "SAN JUAN BAUTISTA",
        "SANTO TOMAS LA UNION",
        "ZUNILITO",
        "PUEBLO NUEVO",
        "RIO BRAVO",
    ],
    "RETALHULEU": [
        "RETALHULEU",
        "SAN SEBASTIAN",
        "SANTA CRUZ MULUA",
        "SAN MARTIN ZAPOTITLAN",
        "SAN FELIPE",
        "SAN ANDRES VILLA SECA",
        "CHAMPERICO",
        "NUEVO SAN CARLOS",
        "EL ASINTAL",
    ],
    "SAN MARCOS": [
        "SAN MARCOS",
        "SAN PEDRO SACATEPEQUEZ",
        "SAN ANTONIO SACATEPEQUEZ",
        "COMITANCILLO",
        "SAN MIGUEL IXTAHUACAN",
        "CONCEPCION TUTUAPA",
        "TACANA",
        "SIBINAL",
        "TAJUMULCO",
        "TEJUTLA",
        "SAN RAFAEL PIE DE LA CUESTA",
        "NUEVO PROGRESO",
        "EL TUMBADOR",
        "EL RODEO",
        "MALACATAN",
        "CATARINA",
        "AYUTLA",
        "OCOS",
        "SAN PABLO",
        "EL QUETZAL",
        "LA REFORMA",
        "PAJAPITA",
        "IXCHIGUAN",
        "SAN JOSE OJETENAM",
        "SAN CRISTOBAL CUCHO",
        "SIPACAPA",
        "ESQUIPULAS PALO GORDO",
        "RIO BLANCO",
        "SAN LORENZO",
    ],
    "HUEHUETENANGO": [
        "HUEHUETENANGO",
        "CHIANTLA",
        "MALACATANCITO",
        "TODOS SANTOS CUCHUMATAN",
        "SAN JUAN ATITAN",
        "SANTA EULALIA",
        "SAN MATEO IXTATAN",
        "COLOTENANGO",
        "SAN SEBASTIAN HUEHUETENANGO",
        "TECTITAN",
        "CONCEPCION HUISTA",
        "SAN MIGUEL ACATAN",
        "JACALTENANGO",
        "SAN PEDRO SOLOMA",
        "SAN ILDEFONSO IXTAHUACAN",
        "SANTA BARBARA",
        "LA LIBERTAD",
        "LA DEMOCRACIA",
        "SAN GASPAR IXCHIL",
        "SANTIAGO CHIMALTENANGO",
        "SANTA ANA HUISTA",
        "SAN RAFAEL LA INDEPENDENCIA",
        "NENTON",
        "SAN SEBASTIAN COATAN",
        "BARILLAS",
        "AGUACATAN",
        "SAN RAFAEL PETZAL",
        "SAN JUAN IXCOY",
        "CUILCO",
        "UNION CANTINIL",
        "PETATAN",
    ],
    "QUICHE": [
        "SANTA CRUZ DEL QUICHE",
        "CHICHE",
        "CHINIQUE",
        "ZACUALPA",
        "CHAJUL",
        "CHICHICASTENANGO",
        "PATZITE",
        "SAN ANTONIO ILOTENANGO",
        "SAN PEDRO JOCOPILAS",
        "CUNEN",
        "SAN JUAN COTZAL",
        "JOYABAJ",
        "NEBAJ",
        "SAN ANDRES SAJCABAJA",
        "SAN MIGUEL USPANTAN",
        "SACAPULAS",
        "SAN BARTOLOME JOCOTENANGO",
        "CANILLA",
        "CHICAMAN",
        "IXCAN",
        "PACHALUM",
    ],
    "BAJA VERAPAZ": [
        "SALAMA",
        "SAN MIGUEL CHICAJ",
        "RABINAL",
        "CUBULCO",
        "GRANADOS",
        "SANTA CRUZ EL CHOL",
        "SAN JERONIMO",
        "PURULHA",
    ],
    "ALTA VERAPAZ": [
        "COBAN",
        "SANTA CRUZ VERAPAZ",
        "SAN CRISTOBAL VERAPAZ",
        "TACTIC",
        "TAMAHU",
        "TUCURU",
        "PANZOS",
        "SENAHU",
        "SAN PEDRO CARCHA",
        "SAN JUAN CHAMELCO",
        "LANQUIN",
        "SANTA MARIA CAHABON",
        "CHISEC",
        "CHAHAL",
        "FRAY BARTOLOME DE LAS CASAS",
        "SANTA CATALINA LA TINTA",
        "RAXRUHA",
    ],
    "PETEN": [
        "FLORES",
        "SAN JOSE",
        "SAN BENITO",
        "SAN ANDRES",
        "LA LIBERTAD",
        "SAN FRANCISCO",
        "SANTA ANA",
        "DOLORES",
        "SAN LUIS",
        "SAYAXCHE",
        "MELCHOR DE MENCOS",
        "POPTUN",
        "LAS CRUCES",
        "EL CHAL",
    ],
    "IZABAL": [
        "PUERTO BARRIOS",
        "LIVINGSTON",
        "EL ESTOR",
        "MORALES",
        "LOS AMATES",
    ],
    "ZACAPA": [
        "ZACAPA",
        "ESTANZUELA",
        "RIO HONDO",
        "GUALAN",
        "TECULUTAN",
        "USUMATLAN",
        "CABANAS",
        "SAN DIEGO",
        "LA UNION",
        "HUITE",
    ],
    "CHIQUIMULA": [
        "CHIQUIMULA",
        "SAN JOSE LA ARADA",
        "SAN JUAN ERMITA",
        "JOCOTAN",
        "CAMOTAN",
        "OLOPA",
        "ESQUIPULAS",
        "CONCEPCION LAS MINAS",
        "QUETZALTEPEQUE",
        "SAN JACINTO",
        "IPALA",
    ],
    "JALAPA": [
        "JALAPA",
        "SAN PEDRO PINULA",
        "SAN LUIS JILOTEPEQUE",
        "SAN MANUEL CHAPARRON",
        "SAN CARLOS ALZATATE",
        "MONJAS",
        "MATAQUESCUINTLA",
    ],
    "JUTIAPA": [
        "JUTIAPA",
        "EL PROGRESO",
        "SANTA CATARINA MITA",
        "AGUA BLANCA",
        "ASUNCION MITA",
        "YUPILTEPEQUE",
        "ATESCATEMPA",
        "JEREZ",
        "EL ADELANTO",
        "ZAPOTITLAN",
        "COMAPA",
        "JALPATAGUA",
        "CONGUACO",
        "MOYUTA",
        "PASACO",
        "SAN JOSE ACATEMPA",
        "QUESADA",
    ],
}

DEPARTMENT_NAMES: set[str] = set(DEPARTMENTS.keys())

# Índice inverso: municipio -> departamento (para detectar incoherencias).
MUNICIPALITY_TO_DEPARTMENT: dict[str, str] = {
    municipality: department
    for department, municipalities in DEPARTMENTS.items()
    for municipality in municipalities
}
