import { test, expect } from "@playwright/test";

test("conservar formularios, diálogos y cierre con teclado después de extraer la UI común", async ({ page }) => {
  await page.goto("/clientes");
  await page.getByRole("button", { name: "Iniciar Sesión", exact: true }).first().click();
  const login = page.getByRole("dialog", { name: "Acceso Notarial Seguro" });
  await login.getByRole("button", { name: "Cerrar" }).focus();
  await page.keyboard.press("Enter");
  await expect(login).toBeHidden();
  await page.getByRole("button", { name: "Iniciar Sesión", exact: true }).first().click();
  await login.getByLabel(/Usuario o Correo/i).fill("e2e_sintetico");
  await login.getByLabel("Contraseña").fill("Synthetic-test-42!");
  await login.getByLabel("Contraseña").press("Enter");
  await expect(page.getByRole("heading", { name: "Gestión de Clientes" })).toBeVisible();

  await page.getByRole("button", { name: "Nuevo Cliente" }).click();
  const client = page.getByRole("dialog", { name: "Registrar Cliente" });
  await client.getByRole("button", { name: "Registrar Cliente" }).click();
  await expect(client.getByRole("alert").first()).toBeVisible();
  await client.getByLabel("Nombres").fill("Cliente Sintético Modal");
  await client.getByLabel("Apellidos").fill("Estructural");
  await client.getByLabel(/DPI/).fill("0000000000201");
  await client.getByLabel("NIT", { exact: true }).fill("00124-K");
  await client.getByRole("button", { name: "Registrar Cliente" }).click();
  await expect(client).toBeHidden();
  const clientRow = page.getByRole("row").filter({ hasText: "Cliente Sintético Modal Estructural" });
  await expect(clientRow).toContainText("0000000000201");
  await clientRow.getByTitle("Editar cliente", { exact: true }).click();
  const editClient = page.getByRole("dialog", { name: "Editar Cliente" });
  await expect(editClient.getByLabel(/DPI/)).toBeDisabled();
  await editClient.getByLabel("Profesión u Oficio").fill("Prueba sintética");
  await editClient.getByRole("button", { name: "Guardar Cambios" }).click();
  await expect(editClient).toBeHidden();
  await clientRow.getByTitle("Baja lógica", { exact: true }).click();
  const confirmation = page.getByRole("alertdialog");
  await expect(confirmation).toBeVisible();
  await confirmation.getByRole("button", { name: "Volver" }).click();
  await expect(confirmation).toBeHidden();
  await expect(clientRow).toContainText("ACTIVO");

  await page.getByRole("button", { name: "Personas Jurídicas" }).click();
  await page.getByRole("button", { name: "Nueva Persona Jurídica" }).click();
  const entity = page.getByRole("dialog", { name: "Registrar Persona Jurídica" });
  await entity.getByLabel(/Razón Social/).fill("Sociedad Sintética Modal");
  await entity.getByLabel(/NIT/).fill("00125-K");
  await entity.getByRole("button", { name: "Registrar Persona Jurídica" }).click();
  await expect(entity).toBeHidden();
  await expect(page.getByRole("row").filter({ hasText: "Sociedad Sintética Modal" })).toContainText("00125-K");

  await page.goto("/expedientes");
  await page.getByRole("button", { name: "Nuevo Expediente" }).click();
  const caseForm = page.getByRole("dialog", { name: "Aperturar Expediente Notarial" });
  await caseForm.getByLabel(/Título/).fill("Expediente Sintético Modal");
  await caseForm.getByRole("button", { name: "Aperturar Expediente" }).click();
  await expect(caseForm).toBeHidden();
  const caseRow = page.getByRole("row").filter({ hasText: "Expediente Sintético Modal" });
  await caseRow.getByTitle("Ver detalle y comparecientes", { exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("Expediente Sintético Modal");
  await page.getByRole("dialog").getByRole("button", { name: "Cerrar" }).click();
  await caseRow.getByTitle("Validar consistencia documental (RULE-001..020)", { exact: true }).click();
  const validation = page.getByRole("dialog", { name: "Validación de Consistencia Documental" });
  await expect(validation.getByLabel("Formulario y versión a evaluar")).toBeVisible();
  await validation.getByRole("button", { name: "Cerrar" }).click();
  await caseRow.getByTitle("Generar borrador DOCX verificado", { exact: true }).click();
  const generation = page.getByRole("dialog", { name: "Generar Borrador DOCX" });
  await expect(generation.getByLabel("Plantilla (versión ACTIVA)")).toBeVisible();
  await generation.getByRole("button", { name: "Cerrar" }).click();

  await page.goto("/plantillas");
  await page.getByRole("button", { name: "Nueva Plantilla" }).click();
  const upload = page.getByRole("dialog", { name: "Cargar Plantilla DOCX" });
  await upload.getByLabel("Archivo DOCX").setInputFiles({ name: "sintetico.csv", mimeType: "text/csv", buffer: Buffer.from("dato\nsintético") });
  await expect(upload.getByRole("alert")).toHaveText("Solo se permiten archivos con extensión .docx.");
  await upload.getByRole("button", { name: "Cancelar" }).click();
  await expect(upload).toBeHidden();
  await page.getByTitle("Control de Usuarios y Auditoría", { exact: true }).click();
  const users = page.getByRole("dialog", { name: "Control de Seguridad y Accesos" });
  await expect(users).toContainText("Notario sintético");
  await users.getByRole("button", { name: "Cerrar" }).focus();
  await page.keyboard.press("Enter");
  await expect(users).toBeHidden();
});
